# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Youngeun Nam
title: Researcher
email: youngeun.nam@kaist.ac.kr
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://bit.ly/maradonam
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username: young-eun-nam
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: jon615
# flickr_username: jekyll
# instagram_username: zero__is_two
linkedin_username: youngeunnam
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: UCZd-VqGGaK48aIT6nFARtfg
# googleplus_username: +jekyll
# orcid_username: 0009-0008-8333-6488

# Additional icon links
additional_links:
- title: CV
  icon: fa fa-file-pdf-o
  url: https://young-eun-nam.github.io/assets/Youngeun_Nam_CV_2024.pdf
- title: Scholar
  icon: fa-google-scholar
  url: https://scholar.google.com/citations?hl=ko&user=Cz1zyRsAAAAJ
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/IMG_7861.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hello, I am Youngeun Nam. I am a Ph.D. candidate in [Data Mining Lab](https://www.kaistdmlab.org/) at KAIST.
  My academic experience is deeply rooted in the field of <mark>data mining</mark> which involves uncovering meaningful patterns and insights from vast and complex datasets.
  Currently, my research is focused on exploring the potential of multi-modal data-centric deep learning across various domains.
  This area of study is fascinating because it integrates and analyzes different types of data—such as images, text, and numerical data—simultaneously, leading to more robust and comprehensive models that can better understand and predict complex phenomena. My work aims to push the boundaries of what is possible with deep learning, particularly in the context of real-world applications.
  In addition to my academic pursuits, I am strongly interested in applying these advanced data mining techniques to the sports domain, where data analysis is increasingly becoming a critical component of performance enhancement, strategic planning, and injury prevention.
  My passion for sports analytics has been further fueled by my professional experience as a data analyst at a leading sports data analysis company, named Fitogeter.

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: KAIST
        sub_title: Ph.D.
        caption: 2022.03 - Present
#         quote: >
#            Korea Advanced Institute of Science and Technology
        description: | # this will include new lines to allow paragraphs
          *Korea Advanced Institute of Science and Technology*
          | School of Computing
          
          [Data Mining Lab](https://www.kaistdmlab.org/) advised by [Jae-Gil Lee](https://dm.kaist.ac.kr/jaegil/)
          
      - layout: left
        title: KAIST
        sub_title: M.S
        caption: 2020.03 - 2022.02
#         quote: >
#            Korea Advanced Institute of Science and Technology
        description: | # this will include new lines to allow paragraphs
          *Korea Advanced Institute of Science and Technology*
          | Industrial and System Engineering
          
          (Graduate School of Data Science)
          
          [Data Mining Lab](https://www.kaistdmlab.org/) advised by [Jae-Gil Lee](https://dm.kaist.ac.kr/jaegil/)

      - layout: left
        title: POSTECH
        sub_title: B.S
        caption: 2013.03 - 2017.02
#         quote: >
#           Pohang University of Science and Technology
        description: | # this will include new lines to allow paragraphs
          *Pohang University of Science and Technology*
          | Industrial and Management Engineering


  - title: Experience
    layout: list
    content:
    
      - layout: left
        title: Fitogether Inc.
        sub_title: Data Analyst
        caption: 2018.09 - 2019.11
        link: https://www.fitogether.com
        quote: >
          Fitogether, Innovating the Sports Culture Using IT Technology.
        description: | # this will include new lines to allow paragraphs
          Based on a wearable EPTS with its own technology, Fitogether measures player/team data during sports (association football) activities, and runs an analytics service ‘OhCoach’ using the data.
          In particular, I contributed to the launch of the soccer data analysis web service.
          
          - Producing manuals for Fitogether 'Ohcoach' service users at the '2018 K League U17/U18 Championship' as a sports data analysis startup intern.
          
          - Creating crawling module with detailed information about K League K1, K2, R League, and ACL competition.
          
          - Creating the 'Register' module, the foundation for data analysis using Python, and implementing the algorithm.
          
      - layout: left
        title: Hyundai Autoever
        sub_title: Software Engineer
        caption: 2017.01 - 2017.12
        link: https://www.hyundai-autoever.com
        quote: >
          Hyundai AutoEver leads a paradigm shift for the future of the 4th industrial revolution.
        description: | # this will include new lines to allow paragraphs
          Working at Hyundai Autoever IT Jobs Finance Team (Hyundai Card, Capital, Commercial). 
          
          ‘Hyundai Card/Capital/Commercial Blockchain Platform Construction and Service Challenge Implementation’ Project Developer.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
    # location (top-right/right/left/top-middle)
      - layout: left
        title: Samsung Mobile Experience
        sub_title: KAIST
        caption: Jul. 2022 - Jul. 2023
#         link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#         link_text: Link Text
#         additional_links:
#           - title:  Github page for project (eg. sproogen/modern-resume-theme)
#             icon: fab fa-github
#             url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#           - title:  Github page for project (eg. sproogen/modern-resume-theme)
#             icon: fab fa-github
#             url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#         quote: >
#           KAIST (Jun. 2021 - present)
        description: | # this will include new lines to allow paragraphs
          Few-shot Anomaly Detection and Root Cause Estimation development.
    
      - layout: left
        title: Samsung Mobile Experience
        sub_title: KAIST
        caption: Jun. 2021 - Jun. 2022
#         link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#         link_text: Link Text
#         additional_links:
#           - title:  Github page for project (eg. sproogen/modern-resume-theme)
#             icon: fab fa-github
#             url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#           - title:  Github page for project (eg. sproogen/modern-resume-theme)
#             icon: fab fa-github
#             url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#         quote: >
#           KAIST (Jun. 2021 - present)
        description: | # this will include new lines to allow paragraphs
          Real-time service incident prediction development.
          
      - layout: left
        title: Samsung SDS
        sub_title: Seoul National University
        caption: Aug. 2018 - Jul. 2018
#         link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#         link_text: Link Text
#         additional_links:
#           - title:  Github page for project (eg. sproogen/modern-resume-theme)
#             icon: fab fa-github
#             url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#           - title:  Github page for project (eg. sproogen/modern-resume-theme)
#             icon: fab fa-github
#             url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#         quote: >
#           Seoul National University (Aug. 2018 - Jul. 2018)
        description: | # this will include new lines to allow paragraphs
          Storage-based platform model business idea research project.
          
          Platform proposal that provides new value to storage consumers.
          
      - layout: left
        title: Hyundai Card
        sub_title: Hyundai Autoever
        caption: Jun. 2017 - Dec. 2017
#         link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#         link_text: Link Text
#         additional_links:
#           - title:  Github page for project (eg. sproogen/modern-resume-theme)
#             icon: fab fa-github
#             url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#           - title:  Github page for project (eg. sproogen/modern-resume-theme)
#             icon: fab fa-github
#             url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#         quote: >
#           Hyundai Autoever (Jun. 2017 - Dec. 2017)
        description: | # this will include new lines to allow paragraphs
          Hyundai Card/Capital/Commercial Blockchain Platform Construction and Service Task Implementation.          

  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Bae, M., Shin, Y., **Nam, Y.**, Lee, Y., and Lee, J., Semi-Supervised Learning for Time Series Collected at a Low Sampling Rate. Proceedings of the 30th ACM SIGKDD International Conference on Knowledge Discovery & Data Mining (KDD), Barcelona, Spain, 2024. [[Paper]](https://dl.acm.org/doi/10.1145/3637528.3672033) [[Video]](https://dl.acm.org/doi/suppl/10.1145/3637528.3672033/suppl_file/rtfp2354-video.mp4)
    
      - **Nam, Y.**, Yoon, S., Shin, Y., Bae, M., Song, H., Lee, J., and Lee, B. S., Breaking the Time-Frequency Granularity Discrepancy in Time-Series Anomaly Detection. International World Wide Web Conference (WWW), Singapore, Singapore, 2024. [[Paper]](https://dl.acm.org/doi/10.1145/3589334.3645556) [[Video]](https://www.youtube.com/watch?v=CZaEV9WMHt4) [[Poster]](https://drive.google.com/file/d/1Iv9kcZ392xonZHn9SsCvrCBiW-_HIW9G/view?usp=sharing)
      
      - **Nam, Y.**, Trirat, P., Kim, T., Lee, Y., and Lee, J., Context-Aware Deep Time-Series Decomposition for Anomaly Detection in Businesses. Proceedings of European Conference on Machine Learning and Principles and Practice of Knowledge Discovery in Databases (ECML-PKDD). Torino, Italy, 2023. [[Paper]](https://link.springer.com/chapter/10.1007/978-3-031-43427-3_20) [[Slide]](https://drive.google.com/file/d/1pxG7E8gIt9thUaMg37d-IHHf_w9xY2bn/view?usp=sharing) [[Poster]](https://drive.google.com/file/d/1pc9TtAlnm-RbeQlwgsc2eMNIMLUwDsmN/view?usp=drive_link)
      
      - {Trirat, P., **Nam, Y.**}, Kim, T., and Lee, J., AnoViz: A Visual Inspection Tool of Anomalies in Multivariate Time Series. The Thirty-Seventh AAAI Conference on Artificial Intelligence (AAAI Demonstration Program). Washington, DC, 2023. [[Paper]](https://ojs.aaai.org/index.php/AAAI/article/view/27088) [[Video]](https://youtu.be/fOHZO3xiMAA) [[Poster]](https://time-cad.web.app/files/AnoViz_AAAI23_Poster.pdf) [[Live Demo]](https://time-cad.web.app/)
    
      - Kim, D., Min, H., **Nam, Y.**, Song, H., Yoon, S., Kim, M., Lee, J. COVID-EENet: Predicting Fine-Grained Impact of COVID-19 on Local Economies. The Thirty-Sixth AAAI Conference on Artificial Intelligence (AAAI). Virtual Event, 2022. [[Paper]](https://ojs.aaai.org/index.php/AAAI/article/view/21455) [[Video]](https://aaai-2022.virtualchair.net/poster_aisi1959)
      
      - **Nam, Y.**, Kang, J., Lee, J. ActiveBoostThief: Model Extraction Attack Using Reliable Active Learning. Korea Computer Congress. 2021. [[Paper]](https://www.dbpia.co.kr/pdf/pdfView.do?nodeId=NODE10583011) [[Slide]](https://drive.google.com/file/d/1HWJi7hnQWUM_oowsOxCK6RnJd37WU6Pk/view?usp=sharing)    
    
      - Kim, M., Kang, J., Kim, D., Song, H., Min, H., **Nam, Y.**, Park, D. Lee, J. Hi-COVIDNet: Deep Learning Approach to Predict Inbound COVID-19 Patients and Case Study in South Korea. Proceedings of the 26th ACM SIGKDD International Conference on Knowledge Discovery & Data Mining (KDD). Virtual Event, California, 2020. [[Paper]](https://dl.acm.org/doi/pdf/10.1145/3394486.3412864) [[Video]](https://dl.acm.org/doi/10.1145/3394486.3412864#sec-supp)

  - title: Awards & Scholarship
    layout: text
    content: | # this will include new lines to allow paragraphs

      - Excellence in Character Scholarship, 2024 (₩1,000,000)
      - Young-Han Kim Global Leader Scholarship, 2024 (₩4,000,000)
      - School of Computing, KAIST, Outstanding Teaching Assistant Award, 2023 Spring
      - The Thirty-Seventh AAAI Conference on Artificial Intelligence Scholarship, 2023 ($500)
      - Department of Industrial & Systems Engineering, KAIST, Scholarship, 2021 (₩1,000,000)

  - title: Reviewer Services
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Program Committee
        - International World Wide Web Conference (WWW): 2024
        - ACM SIGKDD Conference on Knowledge Discovery and Data Mining (KDD): 2024
        - Annual Conference on Neural Information Processing Systems (NeurIPS): 2024
        - Asian Conference on Machine Learning Conference Track (ACML): 2024
        - ACM SIGKDD Conference on Knowledge Discovery and Data Mining (KDD): 2025 August
      
      
#   - title: A Little More About Me
#     layout: text
#     content: | # this will include new lines to allow paragraphs
#       This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

#       Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
